import Layout from '@/components/Layout';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { GlobalContextProvider } from '@/state/global.context';
import { Toaster } from 'react-hot-toast';
import { ApolloWrapper } from '@/lib/apollo-provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
	icons: '/favicon.ico',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<GlobalContextProvider>
					<ApolloWrapper>
						<Toaster />
						<Layout>{children}</Layout>
					</ApolloWrapper>
				</GlobalContextProvider>
			</body>
		</html>
	);
}
